name: TakeMeHome
version: '1.2'
main: io.github.qenas.takeMeHome.TakeMeHome
api-version: '1.21'
commands:
  sethome:
    description: Allows the player to save a home.
    usage: /sethome
  home:
    description: Teleports the executor to his home.
    usage: /home
  myhome:
    description: Shows to the executor the coordinates of this home.
    usage: /myhome
